services:
  postgres-test:
    image: postgres:17-alpine
    container_name: psql-test
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  redis-test:
    image: redis:7.4-alpine
    container_name: redis-test
    ports:
      - ${REDIS_PORT}:6379