services:
  app:
    build: .
    container_name: app
    restart: always
    command: [ "uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000" ]
    environment:
      - ENVIRONMENT=DEV
    ports:
      - "8000:8000"
    networks:
      - pomodoro-net
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_started
      redis:
        condition: service_started