"""Alter creator_id field Task

Revision ID: 3644a1b3c43d
Revises: 723415527c59
Create Date: 2025-06-08 21:34:13.790736

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3644a1b3c43d"
down_revision: Union[str, None] = "723415527c59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("tasks_creator_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(None, "tasks", "users", ["creator_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(op.f("tasks_creator_id_fkey"), "tasks", "users", ["creator_id"], ["id"])
    # ### end Alembic commands ###
