"""Renamed password field in user

Revision ID: 723415527c59
Revises: fe2569814d13
Create Date: 2025-05-30 21:14:49.054174

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "723415527c59"
down_revision: Union[str, None] = "fe2569814d13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(length=100), nullable=False))
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password", sa.VARCHAR(length=100), autoincrement=False, nullable=False)
    )
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
