name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'
    runs-on: ubuntu-latest
    environment: pomodoro

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_ACTIONS_DEV_SERVER }}

      - name: Deploy to server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@94.228.126.175 "
            cd pomodoro-time &&
            git pull &&
            make dev-down &&
            make dev-up
          "
