name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync

      - name: Run Ruff linter
        run: uv run ruff check .

      - name: Run Ruff formatter
        run: uv run ruff format --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync

      - name: Start test services
        run: docker compose -f docker-compose.test.yml --env-file .test.env up -d

      - name: Wait for services to be ready
        run: |
          # Ждем пока PostgreSQL будет готов
          until docker compose -f docker-compose.test.yml --env-file .test.env exec -T postgres pg_isready -U $DB_USER -d $DB_NAME; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          
          until docker compose -f docker-compose.test.yml --env-file .test.env exec -T redis redis-cli ping; do
            echo "Waiting for Redis..."
            sleep 2
          done

      - name: Run pytest
        run: uv run pytest

      - name: Stop test services
        run: docker compose -f docker-compose.test.yml down
        if: always()